// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInventoryManagement.Data;

#nullable disable

namespace SmartInventoryManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250320232234_AddIndexToOrderItems")]
    partial class AddIndexToOrderItems
    {
        // Removed BuildTargetModel method
    }
}